language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
services:
  - "mongodb"
install: "pip install -Ur requirements.txt"
script:
  - git submodule update
  - echo "Job's Done!"
